name: reftest

on: [push, pull_request]

jobs:
  reftest:
    runs-on: ${{ matrix.os }}
    name: Node ${{ matrix.node }} / ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18.x, 20.x]
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Checkout game-driver repository
        uses: actions/checkout@v4
        with:
          path: game-driver
      - name: Checkout engine-files repository
        uses: actions/checkout@v4
        with:
          repository: akashic-games/engine-files
          path: engine-files
      - name: Pack game-driver
        working-directory: game-driver
        id: game_driver
        run: |
          npm ci
          packName=$(npm pack)
          echo "++++++++++++++++++++++"
          echo  $packName
          echo "++++++++++++++++++++++end"
          fileName=$(ls -1 *.tgz)
          echo "pack_name=$fileName" >> $GITHUB_OUTPUT
      - name: Run engine-files reftest
        working-directory: engine-files
        run: |
          npm ci
          npm i ../game-driver/${{steps.game_driver.outputs.pack_name}} --no-save
          npm run build
          npm test
      - name: Archive artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: engine_files_reftest_result
          path: |
            ./engine-files/tests/fixtures/**/expected/
            ./engine-files/tests/fixtures/**/actual/
            ./engine-files/tests/fixtures/**/diff/
