name: reftest

on: [push, pull_request]

jobs:
  reftest:
    runs-on: ${{ matrix.os }}
    name: Node ${{ matrix.node }} / ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16.x, 18.x]
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Use npm@7
        run: npm i -g npm@7 --registry=https://registry.npmjs.org
      - name: Checkout game-driver repository
        uses: actions/checkout@v3
        with:
          path: game-driver
      - name: Checkout engine-files repository
        uses: actions/checkout@v3
        with:
          repository: akashic-games/engine-files
          path: engine-files
      - name: Pack game-driver
        working-directory: game-driver
        id: game_driver
        run: |
          npm ci
          echo "::set-output name=pack_name::$(npm pack)"
      - name: Run engine-files reftest
        working-directory: engine-files
        run: |
          npm ci
          npm i ../game-driver/${{steps.game_driver.outputs.pack_name}} --no-save
          npm run build
          npm test
      - name: Archive artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: engine_files_reftest_result
          path: |
            ./engine-files/tests/fixtures/**/expected/
            ./engine-files/tests/fixtures/**/actual/
            ./engine-files/tests/fixtures/**/diff/
